package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"log"
	"math/rand"
	"strconv"
	"time"

	"mind-mate-server/graph/model"
	"mind-mate-server/internal/auth"
	"mind-mate-server/internal/repository"
	"mind-mate-server/internal/service"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string) (*string, error) {
	user, err := repository.GetUserByEmailForGraphQL(email)
	if err != nil {
		return nil, fmt.Errorf("failed to check user: %v", err)
	}
	if user == nil {
		return nil, fmt.Errorf("User not found. Please sign up.")
	}

	otp := generateOTP()
	if err := repository.SaveOTP(email, otp); err != nil {
		return nil, err
	}

	if err := service.SendOTP(email, otp); err != nil {
		log.Printf("Failed to send OTP: %v", err)
		return nil, fmt.Errorf("Failed to initiate login: %v", err)
	}

	msg := fmt.Sprintf("OTP sent to %s", email)
	return &msg, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, firstName string, lastName string, email string, dateOfBirth string, city string, country string, profession string, maritalStatus string) (*string, error) {
	err := repository.CreateUser(email, firstName, lastName, dateOfBirth, city, country, profession, maritalStatus)
	if err != nil {
		return nil, fmt.Errorf("Failed to sign up: %v", err)
	}

	otp := generateOTP()
	if err := repository.SaveOTP(email, otp); err != nil {
		return nil, err
	}

	if err := service.SendOTP(email, otp); err != nil {
		log.Printf("Failed to send OTP: %v", err)
		return nil, fmt.Errorf("Failed to sign up: %v", err)
	}

	msg := "Signup successful. OTP sent to email."
	return &msg, nil
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, email string, otp string) (*model.AuthPayload, error) {
	isValid, err := repository.VerifyOTP(email, otp)
	if err != nil {
		return nil, err
	}
	if !isValid {
		return nil, fmt.Errorf("Invalid or expired OTP")
	}

	user, err := repository.GetUserByEmailForGraphQL(email)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, fmt.Errorf("User not found")
	}

	token, err := auth.GenerateToken(email, user.Email)
	if err != nil {
		return nil, fmt.Errorf("Failed to generate token")
	}

	return &model.AuthPayload{
		Token: &token,
		User:  user,
	}, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, email string) (*model.User, error) {
	user, err := repository.GetUserByEmailForGraphQL(email)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, fmt.Errorf("User not found")
	}
	return user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// Helper
func generateOTP() string {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return strconv.Itoa(100000 + r.Intn(900000))
}
