package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"log"
	"mind-mate-server/graph/model"
	"mind-mate-server/internal/auth"
	"mind-mate-server/internal/repository"
	"mind-mate-server/internal/service"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, firstName string, lastName string, email string, dateOfBirth string, city string, country string, profession string, maritalStatus string) (*string, error) {
	err := repository.CreateUser(email, firstName, lastName, dateOfBirth, city, country, profession, maritalStatus)
	if err != nil {
		return nil, fmt.Errorf("Failed to sign up: %v", err)
	}

	otp := generateOTP()
	if err := repository.SaveOTP(email, otp); err != nil {
		return nil, err
	}

	if err := service.SendOTP(email, otp); err != nil {
		log.Printf("Failed to send OTP: %v", err)
		return nil, fmt.Errorf("Failed to sign up: %v", err)
	}

	msg := "Signup successful. OTP sent to email."
	return &msg, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string) (*string, error) {
	user, err := repository.GetUserByEmailForGraphQL(email)
	if err != nil {
		return nil, fmt.Errorf("failed to check user: %v", err)
	}
	if user == nil {
		return nil, fmt.Errorf("User not found. Please sign up.")
	}

	otp := generateOTP()
	if err := repository.SaveOTP(email, otp); err != nil {
		return nil, err
	}

	if err := service.SendOTP(email, otp); err != nil {
		log.Printf("Failed to send OTP: %v", err)
		return nil, fmt.Errorf("Failed to initiate login: %v", err)
	}

	msg := fmt.Sprintf("OTP sent to %s", email)
	return &msg, nil
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, email string, otp string) (*model.AuthPayload, error) {
	isValid, err := repository.VerifyOTP(email, otp)
	if err != nil {
		return nil, err
	}
	if !isValid {
		return nil, fmt.Errorf("Invalid or expired OTP")
	}

	user, err := repository.GetUserByEmailForGraphQL(email)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, fmt.Errorf("User not found")
	}

	token, err := auth.GenerateToken(email, user.Email)
	if err != nil {
		return nil, fmt.Errorf("Failed to generate token")
	}

	return &model.AuthPayload{
		Token: &token,
		User:  user,
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	email := auth.GetUserEmailFromContext(ctx)
	if email == "" {
		return nil, fmt.Errorf("not authenticated")
	}

	user, err := repository.UpdateUser(
		email,
		input.FirstName,
		input.LastName,
		input.DateOfBirth,
		input.City,
		input.Country,
		input.Profession,
		input.MaritalStatus,
	)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// RequestEmailChange is the resolver for the requestEmailChange field.
func (r *mutationResolver) RequestEmailChange(ctx context.Context, newEmail string) (string, error) {
	currentEmail := auth.GetUserEmailFromContext(ctx)
	if currentEmail == "" {
		return "", fmt.Errorf("not authenticated")
	}

	// Verify new email is not already in use
	existingUser, err := repository.GetUserByEmailForGraphQL(newEmail)
	if err != nil {
		return "", fmt.Errorf("failed to check email: %v", err)
	}
	if existingUser != nil {
		return "", fmt.Errorf("email already in use")
	}

	// Generate and send OTP to NEW email
	otp := generateOTP()
	if err := repository.SaveOTP(newEmail, otp); err != nil {
		return "", err
	}

	if err := service.SendOTP(newEmail, otp); err != nil {
		log.Printf("Failed to send OTP: %v", err)
		return "", fmt.Errorf("failed to send verification code")
	}

	return fmt.Sprintf("Verification code sent to %s", newEmail), nil
}

// ConfirmEmailChange is the resolver for the confirmEmailChange field.
func (r *mutationResolver) ConfirmEmailChange(ctx context.Context, newEmail string, otp string) (*model.User, error) {
	currentEmail := auth.GetUserEmailFromContext(ctx)
	if currentEmail == "" {
		return nil, fmt.Errorf("not authenticated")
	}

	// Verify OTP for the new email
	isValid, err := repository.VerifyOTP(newEmail, otp)
	if err != nil {
		return nil, err
	}
	if !isValid {
		return nil, fmt.Errorf("invalid or expired verification code")
	}

	// Update email
	user, err := repository.UpdateUserEmail(currentEmail, newEmail)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// CreateJournal is the resolver for the createJournal field.
func (r *mutationResolver) CreateJournal(ctx context.Context, input model.JournalInput) (*model.Journal, error) {
	// For now, use userID 1 - in real implementation, get from auth context
	userID := uint(1)

	var imageUrls []string
	if input.ImageUrls != nil {
		imageUrls = input.ImageUrls
	}

	var metrics *service.JournalMetrics
	if r.RAGService != nil {
		textForMetrics := fmt.Sprintf("Topic: %s\nBody: %s", input.Topic, input.Body)
		extMetrics, err := r.RAGService.ExtractJournalMetrics(ctx, textForMetrics)
		if err == nil {
			metrics = extMetrics
		} else {
			log.Printf("Failed to extract journal metrics: %v", err)
		}
	}

	journal, err := repository.CreateJournal(
		userID,
		input.Topic,
		input.Body,
		input.FontHeading,
		input.FontSubheading,
		input.FontBody,
		input.FontMono,
		imageUrls,
		metrics,
	)
	if err != nil {
		return nil, err
	}

	// Generate Embedding asynchronously
	if r.RAGService != nil {
		go func() {
			text := fmt.Sprintf("Topic: %s\nBody: %s", journal.Topic, journal.Body)
			embedding, err := r.RAGService.GenerateEmbedding(context.Background(), text)
			if err != nil {
				log.Printf("Failed to generate embedding for journal %d: %v", journal.ID, err)
				return
			}
			if err := repository.UpdateJournalEmbedding(journal.ID, embedding); err != nil {
				log.Printf("Failed to save embedding for journal %d: %v", journal.ID, err)
			}
		}()
	}

	return convertJournalToGraphQL(journal), nil
}

// UpdateJournal is the resolver for the updateJournal field.
func (r *mutationResolver) UpdateJournal(ctx context.Context, id string, input model.JournalInput) (*model.Journal, error) {
	journalID, err := parseUint(id)
	if err != nil {
		return nil, fmt.Errorf("invalid journal ID")
	}

	var imageUrls []string
	if input.ImageUrls != nil {
		imageUrls = input.ImageUrls
	}

	var metrics *service.JournalMetrics
	if r.RAGService != nil {
		textForMetrics := fmt.Sprintf("Topic: %s\nBody: %s", input.Topic, input.Body)
		extMetrics, err := r.RAGService.ExtractJournalMetrics(ctx, textForMetrics)
		if err == nil {
			metrics = extMetrics
		} else {
			log.Printf("Failed to extract journal metrics on update: %v", err)
		}
	}

	journal, err := repository.UpdateJournal(
		journalID,
		input.Topic,
		input.Body,
		input.FontHeading,
		input.FontSubheading,
		input.FontBody,
		input.FontMono,
		imageUrls,
		metrics,
	)
	if err != nil {
		return nil, err
	}

	// Re-generate embedding asynchronously
	if r.RAGService != nil {
		go func() {
			text := fmt.Sprintf("Topic: %s\nBody: %s", journal.Topic, journal.Body)
			embedding, err := r.RAGService.GenerateEmbedding(context.Background(), text)
			if err != nil {
				log.Printf("Failed to generate embedding for journal %d: %v", journal.ID, err)
				return
			}
			if err := repository.UpdateJournalEmbedding(journal.ID, embedding); err != nil {
				log.Printf("Failed to save embedding for journal %d: %v", journal.ID, err)
			}
		}()
	}

	return convertJournalToGraphQL(journal), nil
}

// DeleteJournal is the resolver for the deleteJournal field.
func (r *mutationResolver) DeleteJournal(ctx context.Context, id string) (bool, error) {
	journalID, err := parseUint(id)
	if err != nil {
		return false, fmt.Errorf("invalid journal ID")
	}

	if err := repository.DeleteJournal(journalID); err != nil {
		return false, err
	}

	return true, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, email string) (*model.User, error) {
	user, err := repository.GetUserByEmailForGraphQL(email)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, fmt.Errorf("User not found")
	}
	return user, nil
}

// GetJournals is the resolver for the getJournals field.
func (r *queryResolver) GetJournals(ctx context.Context, sortBy *model.SortOrder) ([]*model.Journal, error) {
	// For now, use userID 1 - in real implementation, get from auth context
	userID := uint(1)

	// Convert SortOrder enum to string for repository
	var sortByStr *string
	if sortBy != nil {
		s := sortBy.String()
		sortByStr = &s
	}

	journals, err := repository.GetJournalsByUserID(userID, sortByStr)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Journal, len(journals))
	for i := range journals {
		result[i] = convertJournalToGraphQL(&journals[i])
	}

	return result, nil
}

// GetJournal is the resolver for the getJournal field.
func (r *queryResolver) GetJournal(ctx context.Context, id string) (*model.Journal, error) {
	journalID, err := parseUint(id)
	if err != nil {
		return nil, fmt.Errorf("invalid journal ID")
	}

	journal, err := repository.GetJournalByID(journalID)
	if err != nil {
		return nil, err
	}
	if journal == nil {
		return nil, fmt.Errorf("journal not found")
	}

	return convertJournalToGraphQL(journal), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	email := auth.GetUserEmailFromContext(ctx)
	if email == "" {
		return nil, fmt.Errorf("not authenticated")
	}

	user, err := repository.GetUserByEmailForGraphQL(email)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, fmt.Errorf("user not found")
	}
	return user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
