// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

type FontSettings struct {
	Heading    *string `json:"heading,omitempty"`
	Subheading *string `json:"subheading,omitempty"`
	Body       *string `json:"body,omitempty"`
	Mono       *string `json:"mono,omitempty"`
}

type Journal struct {
	ID           string          `json:"id"`
	Topic        string          `json:"topic"`
	Body         string          `json:"body"`
	FontSettings *FontSettings   `json:"fontSettings,omitempty"`
	Images       []*JournalImage `json:"images"`
	CreatedAt    string          `json:"createdAt"`
	UpdatedAt    string          `json:"updatedAt"`
}

type JournalImage struct {
	ID        string `json:"id"`
	URL       string `json:"url"`
	SortOrder int32  `json:"sortOrder"`
}

type JournalInput struct {
	Topic          string   `json:"topic"`
	Body           string   `json:"body"`
	FontHeading    *string  `json:"fontHeading,omitempty"`
	FontSubheading *string  `json:"fontSubheading,omitempty"`
	FontBody       *string  `json:"fontBody,omitempty"`
	FontMono       *string  `json:"fontMono,omitempty"`
	ImageUrls      []string `json:"imageUrls,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	Email         string  `json:"email"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	DateOfBirth   *string `json:"dateOfBirth,omitempty"`
	City          *string `json:"city,omitempty"`
	Country       *string `json:"country,omitempty"`
	Profession    *string `json:"profession,omitempty"`
	MaritalStatus *string `json:"maritalStatus,omitempty"`
}
