// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

type FontSettings struct {
	Heading    *string `json:"heading,omitempty"`
	Subheading *string `json:"subheading,omitempty"`
	Body       *string `json:"body,omitempty"`
	Mono       *string `json:"mono,omitempty"`
}

type Journal struct {
	ID           string          `json:"id"`
	Topic        string          `json:"topic"`
	Body         string          `json:"body"`
	MoodScore    *int32          `json:"moodScore,omitempty"`
	AnxietyLevel *int32          `json:"anxietyLevel,omitempty"`
	SleepQuality *int32          `json:"sleepQuality,omitempty"`
	FontSettings *FontSettings   `json:"fontSettings,omitempty"`
	Images       []*JournalImage `json:"images"`
	CreatedAt    string          `json:"createdAt"`
	UpdatedAt    string          `json:"updatedAt"`
}

type JournalImage struct {
	ID        string `json:"id"`
	URL       string `json:"url"`
	SortOrder int32  `json:"sortOrder"`
}

type JournalInput struct {
	Topic          string   `json:"topic"`
	Body           string   `json:"body"`
	FontHeading    *string  `json:"fontHeading,omitempty"`
	FontSubheading *string  `json:"fontSubheading,omitempty"`
	FontBody       *string  `json:"fontBody,omitempty"`
	FontMono       *string  `json:"fontMono,omitempty"`
	ImageUrls      []string `json:"imageUrls,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	FirstName     *string `json:"firstName,omitempty"`
	LastName      *string `json:"lastName,omitempty"`
	DateOfBirth   *string `json:"dateOfBirth,omitempty"`
	City          *string `json:"city,omitempty"`
	Country       *string `json:"country,omitempty"`
	Profession    *string `json:"profession,omitempty"`
	MaritalStatus *string `json:"maritalStatus,omitempty"`
}

type User struct {
	Email         string  `json:"email"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	DateOfBirth   *string `json:"dateOfBirth,omitempty"`
	City          *string `json:"city,omitempty"`
	Country       *string `json:"country,omitempty"`
	Profession    *string `json:"profession,omitempty"`
	MaritalStatus *string `json:"maritalStatus,omitempty"`
}

type SortOrder string

const (
	SortOrderNewestFirst  SortOrder = "NEWEST_FIRST"
	SortOrderOldestFirst  SortOrder = "OLDEST_FIRST"
	SortOrderAlphabetical SortOrder = "ALPHABETICAL"
)

var AllSortOrder = []SortOrder{
	SortOrderNewestFirst,
	SortOrderOldestFirst,
	SortOrderAlphabetical,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderNewestFirst, SortOrderOldestFirst, SortOrderAlphabetical:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
