// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	Email         string  `json:"email"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	DateOfBirth   *string `json:"dateOfBirth,omitempty"`
	City          *string `json:"city,omitempty"`
	Country       *string `json:"country,omitempty"`
	Profession    *string `json:"profession,omitempty"`
	MaritalStatus *string `json:"maritalStatus,omitempty"`
}
